### ISSUE TITLE
Generated HTML file contains "Optional.of"

### ISSUE THREAD

**Issue by tudorache** [co-ode-owl-plugins/owldoc#5] opened 2016-02-22 22:43 UTC
Reproduce: Export OWL Doc for: http://protege.stanford.edu/ontologies/pizza/pizza.owl

OWLDoc v3.0.2, Protege 5.0.0-b23.

The generated HTML file contains "Optional.of":
![screenshot - 02222016 - 02 41 25 pm](https://cloud.githubusercontent.com/assets/2709502/13235412/8f473d68-d972-11e5-845b-4e76fbad5c8e.png)

**Comment by ignazio1977** [comment] 2016-03-15 23:28
The problem is in a dependent library, in ontology-browser-owlhtml.
This can be replicated with:

```
    URL defaultBase = new URL("http://www.co-ode.org/ontologies/owldoc/");
    OWLHTMLKit kit = new OWLHTMLKitImpl("kit", defaultBase);
    String out = "owldoc";
    kit.getOWLServer().loadOntology(URI.create("http://protege.stanford.edu/ontologies/pizza/pizza.owl"));
    File outputDirectory = new File(out);
    if (!outputDirectory.exists()) {
        outputDirectory.mkdir();
    }
    OntologyExporter exporter = new OntologyExporter(kit);
    exporter.export(outputDirectory);
    kit.dispose();
```

Copied from `org.coode.html.OntologyExporter`

**Comment by ignazio1977** [comment] 2016-03-15 23:43
Will require a new release of ontology-browser to fix.

**Comment by johardi** [comment] 2016-05-04 19:09
Hi ignazio,
I'm testing the fixes and building the ontology-browser locally. I found there are several resources missing in the generated HTML:
- js/jquery-1.4.3.min.js
- js/default.js
- images/external.png

Below is the screenshot of the generated HTML from the new build:
![screen shot 2016-05-04 at 12 05 12 pm](https://cloud.githubusercontent.com/assets/5062950/15026002/e25f5fa6-11f0-11e6-97c6-9abc5e808b05.png)

**Comment by ignazio1977** [comment] 2016-05-04 19:13
Good point, I don't know if this issue existed in earlier versions or not - I suspect yes. The bug I've fixed was caused by the update from OWLAPI version 3 to version 4.

**Comment by johardi** [comment] 2016-05-04 21:17
I found the bug source and it's fixed via https://github.com/co-ode-owl-plugins/ontology-browser/commit/dfe4a6c01bd54e3df263a1979ac8a5e9bae03c78

**Comment by johardi** [comment] 2016-05-04 22:01
The [ontology-browser-4.3.0](https://github.com/co-ode-owl-plugins/ontology-browser/releases/tag/ontology-browser-4.3.0) is now released

**Closed as completed by johardi** 2016-05-04 22:01 UTC
